/**
 * LITALK Education — blog.js
 * Shared helpers for blog pages and latest article cards.
 */
'use strict';
(function(){
  const BLOG_API='https://istudent.litalkeducation.com';
  const lang=()=>typeof window.litalkGetLang==='function'?window.litalkGetLang():(document.documentElement.getAttribute('data-lang')||'en');
  async function fetchPosts(){const res=await fetch(`${BLOG_API}/blog/posts`);if(!res.ok)throw new Error(`Blog API responded ${res.status}`);const data=await res.json();return data.posts||[];}
  async function fetchPost(slug){const res=await fetch(`${BLOG_API}/blog/posts/${encodeURIComponent(slug)}`);if(res.status===404)return null;if(!res.ok)throw new Error(`Blog API responded ${res.status}`);const data=await res.json();return data.post||null;}
  function coverUrl(post){return post.hasCover?`${BLOG_API}/blog/posts/${encodeURIComponent(post.slug)}/cover`:null;}
  function isVideoCover(post){return !!(post.coverMime&&post.coverMime.startsWith('video/'));}
  function escapeHtml(str){return String(str??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function pick(post,field){const th=post[`${field}Th`],en=post[field];return lang()==='th'?(th||en||''):(en||th||'');}
  function fmtDate(iso){if(!iso)return '';const d=new Date(iso.replace(' ','T'));if(Number.isNaN(d.getTime()))return iso;return d.toLocaleDateString(lang()==='th'?'th-TH':'en-US',{year:'numeric',month:'long',day:'numeric'});}
  function isSafeLinkHref(value){const v=(value||'').trim();if(!v)return false;if(!/^[a-z][a-z0-9+.-]*:/i.test(v))return true;return /^(https?:|mailto:|tel:)/i.test(v);}
  function isSafeImageSrc(value){const v=(value||'').trim();if(!v)return false;if(!/^[a-z][a-z0-9+.-]*:/i.test(v))return true;if(/^https?:/i.test(v))return true;return /^data:image\/(png|jpe?g|gif|webp|avif);base64,/i.test(v);}
  const ALLOWED_TAGS=new Set(['P','BR','HR','H1','H2','H3','H4','H5','H6','STRONG','B','EM','I','S','DEL','BLOCKQUOTE','UL','OL','LI','CODE','PRE','A','IMG','TABLE','THEAD','TBODY','TFOOT','TR','TH','TD','INPUT']);
  const HARD_REMOVE_TAGS=new Set(['SCRIPT','STYLE','IFRAME','OBJECT','EMBED','FORM','LINK','META','BASE','SVG','MATH','NOSCRIPT','TEMPLATE']);
  function sanitizeNode(root){Array.from(root.childNodes).forEach(node=>{if(node.nodeType===Node.COMMENT_NODE){node.remove();return;}if(node.nodeType!==Node.ELEMENT_NODE)return;const tag=node.tagName;if(HARD_REMOVE_TAGS.has(tag)){node.remove();return;}sanitizeNode(node);if(tag==='INPUT'){const ok=(node.getAttribute('type')||'').toLowerCase()==='checkbox';if(!ok){node.remove();return;}const checked=node.hasAttribute('checked');Array.from(node.attributes).forEach(a=>node.removeAttribute(a.name));node.setAttribute('type','checkbox');node.setAttribute('disabled','');if(checked)node.setAttribute('checked','');return;}if(!ALLOWED_TAGS.has(tag)){while(node.firstChild)root.insertBefore(node.firstChild,node);node.remove();return;}if(tag==='A'&&!isSafeLinkHref(node.getAttribute('href'))){while(node.firstChild)root.insertBefore(node.firstChild,node);node.remove();return;}if(tag==='IMG'&&!isSafeImageSrc(node.getAttribute('src'))){node.remove();return;}Array.from(node.attributes).forEach(attr=>{const name=attr.name.toLowerCase();let keep=false;if(tag==='A')keep=name==='href'||name==='title';else if(tag==='IMG')keep=name==='src'||name==='alt'||name==='title';else if(tag==='CODE')keep=name==='class'&&/^language-[\w-]+$/.test(attr.value);else if(tag==='TH'||tag==='TD')keep=['align','colspan','rowspan'].includes(name);else if(tag==='OL')keep=name==='start'&&/^\d+$/.test(attr.value);if(!keep)node.removeAttribute(attr.name);});if(tag==='A'&&/^https?:/i.test((node.getAttribute('href')||'').trim())){node.setAttribute('target','_blank');node.setAttribute('rel','noopener noreferrer');}if(tag==='IMG')node.setAttribute('loading','lazy');});}
  function sanitizeHtml(raw){const doc=new DOMParser().parseFromString(raw,'text/html');sanitizeNode(doc.body);return doc.body.innerHTML;}
  function mdToHtmlFallback(md){const esc=escapeHtml(md).replace(/\r\n/g,'\n'),lines=esc.split('\n'),out=[];let list=null,inCode=false;const close=()=>{if(list){out.push(`</${list}>`);list=null;}};const inline=s=>s.replace(/!\[([^\]]*)\]\((https?:[^)\s]+)\)/g,'<img src="$2" alt="$1" loading="lazy">').replace(/\[([^\]]+)\]\((https?:[^)\s]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/(^|[^*])\*([^*]+)\*/g,'$1<em>$2</em>').replace(/`([^`]+)`/g,'<code>$1</code>');for(const line of lines){if(line.trim().startsWith('```')){close();out.push(inCode?'</code></pre>':'<pre><code>');inCode=!inCode;continue;}if(inCode){out.push(line);continue;}const h=line.match(/^(#{1,3})\s+(.*)$/);if(h){close();const l=h[1].length+1;out.push(`<h${l}>${inline(h[2])}</h${l}>`);continue;}const q=line.match(/^&gt;\s?(.*)$/);if(q){close();out.push(`<blockquote><p>${inline(q[1])}</p></blockquote>`);continue;}const ul=line.match(/^\s*[-*]\s+(.*)$/);if(ul){if(list!=='ul'){close();out.push('<ul>');list='ul';}out.push(`<li>${inline(ul[1])}</li>`);continue;}const ol=line.match(/^\s*\d+[.)]\s+(.*)$/);if(ol){if(list!=='ol'){close();out.push('<ol>');list='ol';}out.push(`<li>${inline(ol[1])}</li>`);continue;}close();if(line.trim())out.push(`<p>${inline(line)}</p>`);}close();if(inCode)out.push('</code></pre>');return out.join('\n');}
  const FN_REF_OPEN='',FN_REF_CLOSE='',FN_MASK_OPEN='',FN_MASK_CLOSE='';
  function parseFootnotes(md){const lines=String(md||'').split('\n'),defs=new Map(),bodyLines=[];for(let i=0;i<lines.length;i++){const m=lines[i].match(/^ {0,3}\[\^([^\]]+)\]:[ \t]*(.*)$/);if(!m){bodyLines.push(lines[i]);continue;}const key=m[1].trim(),content=[m[2]];while(i+1<lines.length){const next=lines[i+1];if(next.trim()===''){if(i+2<lines.length&&/^( {2,}|\t)/.test(lines[i+2])){content.push('');i++;continue;}break;}if(/^( {2,}|\t)/.test(next)){content.push(next.replace(/^(\t| {2,4})/,''));i++;continue;}break;}if(key)defs.set(key,content.join('\n').trim());}if(!defs.size)return{body:bodyLines.join('\n'),order:[],defs};const masks=[],mask=m=>{masks.push(m);return FN_MASK_OPEN+(masks.length-1)+FN_MASK_CLOSE;};let body=bodyLines.join('\n').replace(/```[\s\S]*?```/g,mask).replace(/`[^`\n]*`/g,mask);const order=[],numByKey=new Map(),occByKey=new Map();body=body.replace(/\[\^([^\]]+)\]/g,(full,raw)=>{const key=raw.trim();if(!defs.has(key))return full;if(!numByKey.has(key)){order.push(key);numByKey.set(key,order.length);occByKey.set(key,0);}const num=numByKey.get(key),occ=(occByKey.get(key)||0)+1;occByKey.set(key,occ);return FN_REF_OPEN+num+':'+occ+FN_REF_CLOSE;});body=body.replace(new RegExp(FN_MASK_OPEN+'(\\d+)'+FN_MASK_CLOSE,'g'),(_m,idx)=>masks[+idx]);return{body,order,defs};}
  function buildFootnotes(order,defs,render){const heading=lang()==='th'?'เชิงอรรถ':'Footnotes',items=order.map((key,i)=>`<li id="fn-${i+1}" class="footnotes__item"><div class="footnotes__content">${render(defs.get(key)||'')}</div></li>`).join('');return `<section class="footnotes" aria-label="${escapeHtml(heading)}"><ol class="footnotes__list">${items}</ol></section>`;}
  function mdToHtml(md){const render=typeof marked!=='undefined'?(m)=>sanitizeHtml(marked.parse(m||'',{gfm:true,breaks:false})):(m)=>mdToHtmlFallback(m||'');const{body,order,defs}=parseFootnotes(md);let html=render(body);html=html.replace(new RegExp(FN_REF_OPEN+'(\\d+):(\\d+)'+FN_REF_CLOSE,'g'),(_m,num,occ)=>`<sup class="footnote-ref" id="fnref-${num}-${occ}"><a href="#fn-${num}" aria-label="Footnote ${num}">${num}</a></sup>`);if(order.length)html+=buildFootnotes(order,defs,render);return html;}
  const postHref=post=>`/blog/post?slug=${encodeURIComponent(post.slug)}`;
  function cardHtml(post){const cover=coverUrl(post),title=pick(post,'title'),titleEn=post.title||post.titleTh||'',titleTh=post.titleTh||post.title||'',excerpt=pick(post,'excerpt'),excerptEn=post.excerpt||post.excerptTh||'',excerptTh=post.excerptTh||post.excerpt||'',cat=escapeHtml(post.category||'Article'),coverMedia=cover?(isVideoCover(post)?`<video src="${cover}" autoplay muted loop playsinline disablepictureinpicture aria-label="${escapeHtml(titleEn)}"></video>`:`<img src="${cover}" alt="${escapeHtml(titleEn)}" loading="lazy" width="400" height="225">`):null,img=coverMedia?`<div class="blog-card__img">${coverMedia}</div>`:`<div class="blog-card__img blog-card__img--placeholder" aria-hidden="true">LITALK</div>`,excerptHtml=excerpt?`<p class="blog-card__excerpt" data-en="${escapeHtml(excerptEn)}" data-th="${escapeHtml(excerptTh)}">${escapeHtml(excerpt)}</p>`:'';return `<article class="blog-card"><a href="${postHref(post)}" aria-label="${escapeHtml(title)}">${img}</a><div class="blog-card__body"><span class="blog-card__tag">${cat}</span><h3 class="blog-card__title" data-en="${escapeHtml(titleEn)}" data-th="${escapeHtml(titleTh)}">${escapeHtml(title)}</h3>${excerptHtml}<div class="blog-card__meta"><span class="blog-card__date" data-post-date="${escapeHtml(post.publishedAt||'')}">${fmtDate(post.publishedAt)}</span><a href="${postHref(post)}" class="blog-card__link" data-en="Read more →" data-th="อ่านเพิ่มเติม →">${lang()==='th'?'อ่านเพิ่มเติม →':'Read more →'}</a></div></div></article>`;}
  document.addEventListener('litalk:langchange',()=>document.querySelectorAll('[data-post-date]').forEach(el=>{const iso=el.getAttribute('data-post-date');if(iso)el.textContent=fmtDate(iso);}));
  async function initHomeLatest(){const grid=document.getElementById('home-blog-grid');if(!grid)return;try{const posts=(await fetchPosts()).slice(0,3);if(posts.length)grid.innerHTML=posts.map(cardHtml).join('');}catch(err){console.warn('blog: could not load latest posts',err);}}
  document.addEventListener('DOMContentLoaded',initHomeLatest);
  window.LitalkBlog={fetchPosts,fetchPost,coverUrl,isVideoCover,cardHtml,mdToHtml,fmtDate,pick,escapeHtml,lang,postHref};
})();