'use strict';
(function loadUnifiedNav(){if(document.querySelector('script[data-litalk-site-nav]'))return;const s=document.createElement('script');s.src='/js/site-nav.js?v=20260826a';s.dataset.litalkSiteNav='1';document.head.appendChild(s);}());
(function(){
  const $=id=>document.getElementById(id);let posts=[],term='',cat='';
  const category=p=>p.category||'Article';
  const searchText=p=>[p.title,p.titleTh,p.excerpt,p.excerptTh,p.category].filter(Boolean).join(' ').toLocaleLowerCase();
  function media(p){const cover=LitalkBlog.coverUrl(p),title=LitalkBlog.pick(p,'title');if(!cover)return '<div class="blog-archive__thumb"></div>';return LitalkBlog.isVideoCover(p)?`<div class="blog-archive__thumb"><video src="${cover}" muted playsinline preload="metadata" aria-label="${LitalkBlog.escapeHtml(title)}"></video></div>`:`<div class="blog-archive__thumb"><img src="${cover}" alt="${LitalkBlog.escapeHtml(title)}" loading="lazy" width="320" height="200"></div>`;}
  function item(p){const title=LitalkBlog.pick(p,'title'),excerpt=LitalkBlog.pick(p,'excerpt');return `<a class="blog-archive__item" href="post?slug=${encodeURIComponent(p.slug)}">${media(p)}<div><span class="blog-archive__cat">${LitalkBlog.escapeHtml(category(p))}</span><h2>${LitalkBlog.escapeHtml(title)}</h2>${excerpt?`<p class="blog-archive__excerpt">${LitalkBlog.escapeHtml(excerpt)}</p>`:''}</div><span class="blog-archive__date" data-post-date="${LitalkBlog.escapeHtml(p.publishedAt||'')}">${LitalkBlog.fmtDate(p.publishedAt)}</span></a>`;}
  function render(){const out=posts.filter(p=>(!cat||category(p)===cat)&&(!term||searchText(p).includes(term)));const th=LitalkBlog.lang()==='th';$('archive-summary').textContent=th?`${out.length} บทความ${cat?` ในหมวด ${cat}`:''}`:`${out.length} ${out.length===1?'article':'articles'}${cat?` in ${cat}`:''}`;$('archive-list').innerHTML=out.length?out.map(item).join(''):`<p class="blog-archive__empty" data-en="No articles match your search." data-th="ไม่พบบทความที่ตรงกับการค้นหา">${th?'ไม่พบบทความที่ตรงกับการค้นหา':'No articles match your search.'}</p>`;}
  function setup(){const categories=[...new Set(posts.map(category))].sort((a,b)=>a.localeCompare(b));$('archive-chips').innerHTML=`<button class="blog-archive__chip active" data-cat="" data-en="All" data-th="ทั้งหมด">All</button>${categories.map(c=>`<button class="blog-archive__chip" data-cat="${LitalkBlog.escapeHtml(c)}">${LitalkBlog.escapeHtml(c)}</button>`).join('')}`;$('archive-chips').addEventListener('click',e=>{const b=e.target.closest('.blog-archive__chip');if(!b)return;cat=b.dataset.cat||'';document.querySelectorAll('.blog-archive__chip').forEach(x=>x.classList.toggle('active',x===b));render();});$('archive-search').addEventListener('input',e=>{term=e.target.value.trim().toLocaleLowerCase();render();});$('archive-toggle').addEventListener('click',()=>{const panel=$('archive-filters'),open=panel.hidden;panel.hidden=!open;$('archive-toggle').setAttribute('aria-expanded',String(open));});$('archive-reset').addEventListener('click',()=>{term='';cat='';$('archive-search').value='';document.querySelectorAll('.blog-archive__chip').forEach((x,i)=>x.classList.toggle('active',i===0));render();});document.addEventListener('litalk:langchange',()=>{const th=LitalkBlog.lang()==='th';$('archive-search').placeholder=th?'ค้นหาบทความ':'Search articles';render();});}
  document.addEventListener('DOMContentLoaded',async()=>{try{posts=await LitalkBlog.fetchPosts();setup();render();}catch(err){console.warn('archive: failed to load',err);$('archive-list').innerHTML='<p class="blog-archive__empty">Could not load articles right now.</p>';}});
})();