'use strict';
(function(){
  const oldHeader=document.querySelector('header');
  if(!oldHeader||document.body?.dataset?.serviceSurface==='portal')return;
  const fortuneLang=document.getElementById('fortune-lang');
  if(fortuneLang){const holder=document.createElement('div');holder.hidden=true;holder.setAttribute('aria-hidden','true');holder.appendChild(fortuneLang);document.body.appendChild(holder);}
  const path=location.pathname.replace(/\/+$/,'')||'/';
  const active=path.startsWith('/courses')?'courses':path.startsWith('/plus')?'plus':path.startsWith('/programs')?'programs':path.startsWith('/about')?'about':path.startsWith('/ask')?'ask':path.startsWith('/blog')?'blog':'';
  const desktop=(key,href,en,th)=>`<li><a href="${href}" class="nav__link${active===key?' nav__link--active':''}" data-en="${en}" data-th="${th}">${en}</a></li>`;
  const mobile=(key,href,en,th)=>`<a href="${href}" class="nav__link${active===key?' nav__link--active':''}" data-en="${en}" data-th="${th}">${en}</a>`;
  const langToggle='<button class="lang-toggle" data-active="en" type="button" aria-label="Switch language / เปลี่ยนภาษา" title="EN / ไทย"><span class="lang-toggle__thumb" aria-hidden="true"></span><span class="lang-toggle__opt active" data-opt="en">EN</span><span class="lang-toggle__opt" data-opt="th">ไทย</span></button>';
  const student='<a href="/portal/student" class="login-menu__item" role="menuitem"><span class="login-menu__item-icon" aria-hidden="true"><i class="fas fa-user-graduate"></i></span><span><strong class="login-menu__item-title" data-en="Student &amp; Parent" data-th="นักเรียนและผู้ปกครอง">Student &amp; Parent</strong><span class="login-menu__item-sub" data-en="Study log, schedule &amp; payments" data-th="บันทึกการเรียน ตารางเรียน และการชำระเงิน">Study log, schedule &amp; payments</span></span></a>';
  const staff='<a href="https://admin.litalkeducation.com" class="login-menu__item" role="menuitem" target="_blank" rel="noopener noreferrer"><span class="login-menu__item-icon" aria-hidden="true"><i class="fas fa-chalkboard-user"></i></span><span><strong class="login-menu__item-title" data-en="Teacher &amp; Staff" data-th="ครูและเจ้าหน้าที่">Teacher &amp; Staff</strong><span class="login-menu__item-sub" data-en="Teaching admin console" data-th="ระบบจัดการการสอน">Teaching admin console</span></span></a>';
  const header=document.createElement('header');header.setAttribute('role','banner');header.innerHTML=`<nav class="nav" id="main-nav" aria-label="Main navigation"><div class="container"><div class="nav__inner"><a href="/" class="nav__logo" aria-label="LITALK Home"><img src="/img/LITALK-Black.png" alt="LITALK Education" class="theme-invertable" width="170" height="28"></a><ul class="nav__links" role="list">${desktop('courses','/courses','Online Learning','เรียนออนไลน์')}${desktop('plus','/plus','LITALK+','LITALK+')}${desktop('programs','/programs','1-on-1 Tutoring','เรียนตัวต่อตัว')}${desktop('about','/about','About','เกี่ยวกับเรา')}${desktop('ask','/ask','Ask','ถามคำศัพท์')}${desktop('blog','/blog','Blog','บทความ')}</ul><div class="nav__actions">${langToggle}<div class="login-menu"><button class="login-menu__btn" type="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user" aria-hidden="true" style="font-size:11px"></i><span data-en="Log in" data-th="เข้าสู่ระบบ">Log in</span><i class="fas fa-chevron-down" aria-hidden="true"></i></button><div class="login-menu__panel" role="menu" aria-label="Login options">${student}${staff}</div></div><a href="/#contact" class="btn btn--primary btn--sm" data-en="Start Learning" data-th="เริ่มเรียน">Start Learning</a></div><button class="nav__hamburger" id="hamburger" aria-label="Toggle menu" aria-expanded="false" aria-controls="mobile-drawer"><span></span><span></span><span></span></button></div></div><div class="nav__drawer" id="mobile-drawer" role="navigation" aria-label="Mobile navigation">${mobile('courses','/courses','Online Learning','เรียนออนไลน์')}${mobile('plus','/plus','LITALK+','LITALK+')}${mobile('programs','/programs','1-on-1 Tutoring','เรียนตัวต่อตัว')}${mobile('about','/about','About','เกี่ยวกับเรา')}${mobile('ask','/ask','Ask','ถามคำศัพท์')}${mobile('blog','/blog','Blog','บทความ')}<div class="nav__actions">${langToggle}<a href="/#contact" class="btn btn--primary btn--sm nav__drawer-cta" data-en="Start Learning" data-th="เริ่มเรียน">Start Learning</a><div class="nav__drawer-login-label" data-en="Log in" data-th="เข้าสู่ระบบ">Log in</div>${student}${staff}</div></div></nav>`;oldHeader.replaceWith(header);
  const nav=header.querySelector('#main-nav'),hamburger=header.querySelector('#hamburger'),drawer=header.querySelector('#mobile-drawer');const close=()=>{hamburger.classList.remove('open');drawer.classList.remove('open');hamburger.setAttribute('aria-expanded','false');document.body.style.overflow='';};hamburger.addEventListener('click',e=>{e.stopPropagation();const open=hamburger.classList.toggle('open');drawer.classList.toggle('open',open);hamburger.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':'';});drawer.querySelectorAll('a').forEach(a=>a.addEventListener('click',close));document.addEventListener('click',e=>{if(!hamburger.contains(e.target)&&!drawer.contains(e.target))close();});addEventListener('resize',()=>{if(innerWidth>768)close();},{passive:true});const sticky=()=>nav.classList.toggle('scrolled',scrollY>20);addEventListener('scroll',sticky,{passive:true});sticky();
  header.querySelectorAll('.login-menu').forEach(menu=>{const btn=menu.querySelector('.login-menu__btn');btn?.addEventListener('click',e=>{e.stopPropagation();const open=menu.classList.toggle('open');btn.setAttribute('aria-expanded',String(open));});document.addEventListener('click',e=>{if(!menu.contains(e.target)){menu.classList.remove('open');btn?.setAttribute('aria-expanded','false');}});});
  // Keep all public surfaces on one persisted language state. TCAS Fortune
  // keeps its own reading state, so its hidden original toggle remains the
  // bridge that re-requests a translated reading when needed.
  const visuals=lang=>header.querySelectorAll('.lang-toggle').forEach(toggle=>{toggle.dataset.active=lang;toggle.querySelectorAll('.lang-toggle__opt').forEach(opt=>opt.classList.toggle('active',opt.dataset.opt===lang));});const getLang=()=>document.documentElement.dataset.lang||localStorage.getItem('litalk-lang')||'en';window.litalkGetLang=getLang;
  function apply(lang){document.documentElement.lang=lang==='th'?'th':'en';document.documentElement.dataset.lang=lang;try{localStorage.setItem('litalk-lang',lang);}catch(_){}document.querySelectorAll('[data-en][data-th]').forEach(node=>{const v=node.getAttribute(`data-${lang}`);if(v!=null)node.textContent=v;});document.querySelectorAll('[data-en-placeholder][data-th-placeholder]').forEach(node=>node.setAttribute('placeholder',node.getAttribute(`data-${lang}-placeholder`)||''));visuals(lang);document.dispatchEvent(new CustomEvent('litalk:langchange',{detail:{lang}}));}
  header.querySelectorAll('.lang-toggle').forEach(toggle=>toggle.addEventListener('click',()=>{const bridge=document.getElementById('fortune-lang');if(bridge){bridge.click();setTimeout(()=>visuals(getLang()),0);return;}apply(getLang()==='th'?'en':'th');}));visuals(getLang());document.addEventListener('litalk:langchange',e=>visuals(e.detail?.lang||getLang()));
})();