'use strict';
(function(){
  const API='https://istudent.litalkeducation.com/service-status';
  const labels={website:{en:'Website',th:'เว็บไซต์หลัก'},ask:{en:'Ask LITALK',th:'Ask LITALK'},chat_site:{en:'Website AI chat',th:'แชท AI บนเว็บไซต์'},portal:{en:'Student portal',th:'พอร์ทัลนักเรียน'},chat_portal:{en:'Portal AI chat',th:'แชท AI ในพอร์ทัล'},checkin:{en:'Check-in',th:'ระบบเช็คอิน'},booking:{en:'Booking',th:'ระบบจองเรียน'},learning:{en:'Online learning',th:'เรียนออนไลน์'},admin:{en:'Admin panel',th:'แผงแอดมิน'}};
  const copy={
    en:{ok:'All systems operational',warn:'Some services have notices',down:'Some services are unavailable',operational:'Operational',notice:'Notice',unavailable:'Unavailable',empty:'No active incidents or maintenance notices.',updated:'Updated',maintenance:'Maintenance',announcement:'Announcement'},
    th:{ok:'ทุกระบบทำงานปกติ',warn:'บางบริการมีประกาศ',down:'บางบริการไม่พร้อมใช้งาน',operational:'ปกติ',notice:'มีประกาศ',unavailable:'ไม่พร้อมใช้งาน',empty:'ขณะนี้ไม่มีเหตุขัดข้องหรือประกาศปิดปรับปรุง',updated:'อัปเดต',maintenance:'ปิดปรับปรุงระบบ',announcement:'ประกาศ'}
  };
  let lang=localStorage.getItem('litalk-lang')==='th'?'th':'en';
  const $=s=>document.querySelector(s);
  function applyLang(){document.documentElement.lang=lang==='th'?'th':'en';document.querySelectorAll('[data-en]').forEach(el=>{el.textContent=el.getAttribute('data-'+lang)||el.textContent});}
  function text(n,key){const custom=lang==='th'?n[key+'Th']:n[key+'En'];return custom||'';}
  function fmt(v){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return d.toLocaleString(lang==='th'?'th-TH':'en-GB',{dateStyle:'medium',timeStyle:'short'});}
  function stateForSurface(notices,id){const relevant=notices.filter(n=>Array.isArray(n.surfaces)&&n.surfaces.includes(id));if(relevant.some(n=>n.phase==='blocking'))return'down';if(relevant.length)return'warning';return'ok';}
  function render(data){const notices=Array.isArray(data.notices)?data.notices:[];const services=$('#status-services');services.innerHTML='';Object.entries(labels).forEach(([id,name])=>{const state=stateForSurface(notices,id);const row=document.createElement('div');row.className='status-service';const n=document.createElement('span');n.className='status-service-name';n.textContent=name[lang];const pill=document.createElement('span');pill.className='status-pill'+(state==='down'?' is-down':state==='warning'?' is-warning':'');pill.textContent=state==='down'?copy[lang].unavailable:state==='warning'?copy[lang].notice:copy[lang].operational;row.append(n,pill);services.appendChild(row)});
    const anyDown=notices.some(n=>n.phase==='blocking');const summary=$('#status-summary');summary.className='status-summary'+(anyDown?' is-down':notices.length?' is-warning':'');$('#status-summary-title').textContent=anyDown?copy[lang].down:notices.length?copy[lang].warn:copy[lang].ok;$('#status-updated').textContent=`${copy[lang].updated}: ${new Date().toLocaleString(lang==='th'?'th-TH':'en-GB')}`;
    const incidents=$('#status-incidents');incidents.innerHTML='';if(!notices.length){const e=document.createElement('div');e.className='status-empty';e.textContent=copy[lang].empty;incidents.appendChild(e);return;}notices.forEach(n=>{const card=document.createElement('article');card.className='status-incident '+(n.phase==='blocking'?'is-down':'is-warning');const head=document.createElement('div');head.className='status-incident-head';const h=document.createElement('h3');h.textContent=text(n,'title')||(n.preset==='maintenance'?copy[lang].maintenance:copy[lang].announcement);const badge=document.createElement('span');badge.className='status-incident-badge';badge.textContent=n.phase==='blocking'?copy[lang].unavailable:(n.preset==='maintenance'?copy[lang].maintenance:copy[lang].announcement);head.append(h,badge);card.appendChild(head);const body=text(n,'body');if(body){const p=document.createElement('p');p.textContent=body;card.appendChild(p)}const meta=document.createElement('p');meta.className='status-incident-meta';const when=n.endsAt?fmt(n.endsAt):n.startsAt?fmt(n.startsAt):'';meta.textContent=[(n.surfaces||[]).map(s=>labels[s]?.[lang]||s).join(' · '),when].filter(Boolean).join(' • ');if(meta.textContent)card.appendChild(meta);incidents.appendChild(card)});
  }
  async function load(){try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw new Error();render(await r.json())}catch(_){render({notices:[]});$('#status-summary').className='status-summary is-warning';$('#status-summary-title').textContent=lang==='th'?'ไม่สามารถตรวจสอบสถานะได้ในขณะนี้':'Status is temporarily unavailable';}}
  $('#status-lang')?.addEventListener('click',()=>{lang=lang==='en'?'th':'en';localStorage.setItem('litalk-lang',lang);applyLang();load()});applyLang();load();setInterval(load,60000);
})();